### ISSUE TITLE
执行go命令时，众多软件包下载超时

### ISSUE THREAD

**Issue by Umbrallerstackcode** [GoSimplicity/AI-CloudOps#100]
已经开启了科学上网，但是执行go mod tidy后，众多软件依赖包下载不了，还有没有其他办法
![image](https://github.com/user-attachments/assets/2ab76284-39d7-4570-871e-e50a6ee6fd91)

**Comment by GoSimplicity** [comment]
> 已经开启了科学上网，但是执行go mod tidy后，众多软件依赖包下载不了，还有没有其他办法 ![image](https://private-user-images.githubusercontent.com/102168892/385147759-2ab76284-39d7-4570-871e-e50a6ee6fd91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODg2MTMsIm5iZiI6MTczMTM4ODMxMywicGF0aCI6Ii8xMDIxNjg4OTIvMzg1MTQ3NzU5LTJhYjc2Mjg0LTM5ZDctNDU3MC04NzFlLWU1MGE2ZWU2ZmQ5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwNTExNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjk3MTBhODA2OWQxNGU4ZTJhODQ0ODJlZDQwZTRhYzBmZThiYTk0MWMzYzk1ZGIxNDRjNjA2OTFmNzk2NGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MK7j8ToO8QLdB-8H-zHNIhm7f71DgK1Safruhf5aQkg)

配置国内代理 export GOPROXY= https://goproxy.cn
