### ISSUE TITLE
项目标题是AI-CloudOps，哪里用到模型，或者GPU了呢

### ISSUE THREAD

**Issue by Umbrallerstackcode** [GoSimplicity/AI-CloudOps#101]
项目标题是AI-CloudOps，哪里用到模型，或者GPU了呢

**Comment by GoSimplicity** [comment]
> 项目标题是AI-CloudOps，哪里用到模型，或者GPU了呢

ai模块我们单纯拆分了，后续项目会以微服务的形式去提供ai模块相关功能

**Comment by Umbrallerstackcode** [comment]
那就是目前还没有AI功能？？或者说目前现有的版本，拆分出来哪些模块

**Comment by GoSimplicity** [comment]
> 那就是目前还没有AI功能？？或者说目前现有的版本，拆分出来哪些模块

ai功能在我们的微服务版本，目前暂未上线，预计明年2月份以前上线

**Comment by Umbrallerstackcode** [comment]
嗨，我看你这项目名字，以为已经上线测试了呢，我还折疼半天部署，目前的版本必须传阿里的token才可以嘛？

**Comment by GoSimplicity** [comment]
> 嗨，我看你这项目名字，以为已经上线测试了呢，我还折疼半天部署，目前的版本必须传阿里的token才可以嘛？

对 读取环境变量

**Comment by Umbrallerstackcode** [comment]
这玩意没什么用，不是所有的人都用阿里云，赶紧去了或者改改吧，不要让他成为初始化时候的必选项

**Comment by GoSimplicity** [comment]
> 这玩意没什么用，不是所有的人都用阿里云，赶紧去了或者改改吧，不要让他成为初始化时候的必选项

项目开始没多久  现在的功能都是一些基本的测试功能 后面会慢慢完善 主要还是参与者比较少   前后端都是我写 比较慢

**Comment by Umbrallerstackcode** [comment]
好的，那加油，期待你的成果
